---

- hosts: localhost
  tasks:
  - name: Add hadoopgroup
    command: addgroup hadoopgroup
    ignore_errors: True
    sudo: yes
  - name: Add ubuntu user to hadoopgroup
    shell: adduser ubuntu hadoopgroup 
    sudo: yes
  - name: Untar required files for setup
    shell: tar -xvf /home/ubuntu/HadoopHive.tar
  - name: Download Hadoop in /usr/local/
    command: chdir=/usr/local/ wget http://mirrors.advancedhosters.com/apache/hadoop/common/hadoop-0.23.10/hadoop-0.23.10.tar.gz
    sudo: yes
  - name: Download Hive in /usr/local/
    command: chdir=/usr/local/ wget http://mirror.olnevhost.net/pub/apache/hive/hive-0.12.0/hive-0.12.0-bin.tar.gz
    sudo: yes
  - name: Untar hadoop in /usr/local/
    command: chdir=/usr/local/ tar -xzf hadoop-0.23.10.tar.gz
    sudo: yes
  - name: Untar Hive in /usr/local/
    command: chdir=/usr/local/ tar -xzf hive-0.12.0-bin.tar.gz
    sudo: yes
  - name: Delete Hadoop tar file in /usr/local/
    command: chdir=/usr/local/ rm hadoop-0.23.10.tar.gz
    sudo: yes
  - name: Delete Hive tar file in /usr/local/
    command: chdir=/usr/local/ rm hive-0.12.0-bin.tar.gz
    sudo: yes
  - name: Create symbolic link for hadoop
    command: chdir=/usr/local/ ln -s hadoop-0.23.10 hadoop
    ignore_errors: True
    sudo: yes
  - name: Change owner of file  file in /usr/local/
    command: chdir=/usr/local/ chown -R ubuntu:hadoopgroup hadoop-0.23.10
    sudo: yes
  - name: Copy hadoop-env.sh to /usr/local/hadoop/etc/hadoop/ 
    copy: src=/home/ubuntu/hadoop-env.sh dest=/usr/local/hadoop/etc/hadoop/hadoop-env.sh
  - name: Create /mnt/volume1/hadoop directory
    shell: mkdir /mnt/volume1/hadoop
    sudo: yes
  - name: Change owner of hadoop directory to hadoopuser
    shell: chown -R ubuntu:hadoopgroup /mnt/volume1/hadoop
    sudo: yes
  - name: Set folder permissions of /hadoop
    shell: chmod 750 /mnt/volume1/hadoop
    sudo: yes
  - name: Create /mnt/volume1/hadoop/hdfs directory
    shell: mkdir /mnt/volume1/hadoop/hdfs
    sudo: yes
  - name: Change owner of hadoop/hdfs directory to hadoopuser
    shell: chown -R ubuntu:hadoopgroup /mnt/volume1/hadoop/hdfs
    sudo: yes
  - name: Set folder permissions of /hadoop/hdfs
    shell: chmod 750 /mnt/volume1/hadoop/hdfs
    sudo: yes
  - name: Copy core-site.xml to /usr/local/hadoop/etc/hadoop/
    copy: src=/home/ubuntu/core-site.xml dest=/usr/local/hadoop/etc/core-site.xml
  - name: Copy mapred-site.xml to /usr/local/hadoop/etc/hadoop/
    copy: src=/home/ubuntu/mapred-site.xml dest=/usr/local/hadoop/etc/hadoop/mapred-site.xml
  - name: Copy hdfs-site.xml to /usr/local/hadoop/etc/hadoop/
    copy: src=/home/ubuntu/hdfs-site.xml dest=/usr/local/hadoop/etc/hadoop/hdfs-site.xml
  - name: Copy hive-site.xml to /usr/local/hive-0.12.0-bin/conf/
    copy: src=/home/ubuntu/hive-site.xml dest=/usr/local/hive-0.12.0-bin/conf/hive-site.xml
  - name: Format hadoop node
    shell: /usr/local/hadoop/bin/hdfs namenode -format
  - name: Start dfs
    action: shell /usr/local/hadoop/sbin/start-dfs.sh
    sudo: yes
    sudo_user: ubuntu
    tags:
      - debug
  - name: Start yarn
    action: shell /usr/local/hadoop/sbin/start-yarn.sh
    sudo: yes
    sudo_user: ubuntu
    tags:
      - debug
  - name: Change mysql root user password
    mysql_user: name=root password=mysql
  - name: Restart .bashrc
    shell: source ~/.bashrc
  - name: Make tmp directory in $HADOOP_HOME
    shell: $HADOOP_HOME/bin/hadoop fs -mkdir       /tmp
  - name: Make /user directory in $HADOOP_HOME
    shell: $HADOOP_HOME/bin/hadoop fs -mkdir       /user
  - name: Make hive directory in /user/
    shell: $HADOOP_HOME/bin/hadoop fs -mkdir       /user/hive
  - name: Make warehouse directory in /user/hive/
    shell: $HADOOP_HOME/bin/hadoop fs -mkdir       /user/hive/warehouse
  - name: Change settings for /tmp
    shell: $HADOOP_HOME/bin/hadoop fs -chmod g+w   /tmp
  - name: Change settings for /user/hive/warehouse
    shell: $HADOOP_HOME/bin/hadoop fs -chmod g+w   /user/hive/warehouse
