#!/bin/bash
#
# chkconfig: 35 90 12
# Default-Start: 3 4 5
# Default-Stop: 0 1 2
# description: Foo server
#
# Get function from functions library
#. /etc/init.d/functions
# Start the service baazmath
start() {
        initlog -c "echo -n Starting baazmath server: "
        /usr/local/bin/BaazMathService.py &
        ### Create the lock file ###
        touch /var/lock/baazmath
        #success $"baaz server startup"
        echo
}
# Restart the service baazdatwaacquisition
stop() {
        #initlog -c "echo -n Stopping baazmath server: "
        killall BaazMathService.py
        ### Now, delete the lock file ###
        rm -f /var/lock/baazmath
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status baazmath
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
