---
### DEPENDENCIES ###
- name: Install awscli
  apt: name=awscli state=present
  sudo: yes
- name: Create the Baaz config directory
  file: path=/var/Baaz state=directory
  sudo: yes
- name: Set timezone to America/Los_Angeles
  shell: timedatectl set-timezone America/Los_Angeles
  sudo: yes
- name: NTP installed
  apt: name=ntp update_cache=yes state=present
  sudo: yes
- name: Remove everything from under the /mnt/volume1 directory
  shell: rm -rf /mnt/volume1/*
  sudo: yes
- name: Save configuration file
  template: src=hosts.cfg dest=/var/Baaz/hosts.cfg
  sudo: yes
- name: Create Log directory
  shell: mkdir -p /var/log/cloudera/navopt
  sudo: yes
- name: Get Flightpath
  shell: aws s3 --region {{ region }} cp s3://{{ s3_deployment_bucket }}/{{ BuildVersion }}flightpath-deployment.tar.gz .
- name: Untar flightpath
  shell: tar -zxf /home/ubuntu/flightpath-deployment.tar.gz chdir=/
  sudo: yes
- name: Get Data Acquisition service
  shell: aws s3 --region {{ region }} cp s3://{{ s3_deployment_bucket }}/{{ BuildVersion }}Baaz-DataAcquisition-Service.tar.gz .
- name: Copy the service files
  shell: tar -zxf /home/ubuntu/Baaz-DataAcquisition-Service.tar.gz chdir=/
  sudo: yes
- name: Get Api service
  shell: aws s3 --region {{ region }} cp s3://{{ s3_deployment_bucket }}/{{ BuildVersion }}Baaz-API-Service.tar.gz .
- name: Copy the service files
  shell: tar -zxf /home/ubuntu/Baaz-API-Service.tar.gz chdir=/
  sudo: yes
- name: Install monit
  apt: name=monit state=present
  sudo: yes
- name: Kill Monit so it won't interfere with installation
  shell: monit quit
  sudo: yes
# - name: Remove old monit ID
#   shell: rm -f /var/lib/monit/id
#   sudo: yes
- name: Remove any previous service that may be installed.
  shell: update-rc.d -f baazdataacquisition remove
  sudo: yes
- name: Stop running upstart script
  service: name=dataacquisitionservice state=stopped
  sudo: yes
- name: Stop running upstart script
  service: name=applicationservice state=stopped
  sudo: yes
- name: Stop running rule engine
  service: name=ruleengineservice state=stopped
  ignore_errors: yes
  sudo: yes
- name: Stop API service
  service: name=apiservice state=stopped
  sudo: yes
- name: Stop NavOpt API server
  service: name=navoptapiserver state=stopped
  sudo: yes
# - name: Start dataacquisitionservice (upstart).
#   service: name=dataacquisitionservice state=started
#   sudo: yes
- name: copy logrotate file
  template: src=roles/backoffice/files/compileserver dest=/etc/logrotate.d/
  sudo: yes

#Start of Analytics module deployment.
- name: Get Analytics Module
  shell: aws s3 --region {{ region }} cp s3://{{ s3_deployment_bucket }}/{{ BuildVersion }}Baaz-Analytics.tar.gz .
- name: Untar Analytics
  shell: tar -zxf /home/ubuntu/Baaz-Analytics.tar.gz chdir=/
  sudo: yes
- name: Get Analytics Service
  shell: aws s3 --region {{ region }} cp s3://{{ s3_deployment_bucket }}/{{ BuildVersion }}Baaz-Analytics-Service.tar.gz .
- name: Install Analytics Service
  shell: tar -zxf /home/ubuntu/Baaz-Analytics-Service.tar.gz chdir=/
  sudo: yes
- name: Remove any previous service that may be installed.
  shell: update-rc.d -f baazmath remove
  sudo: yes
- name: Stop mathservice.
  service: name=mathservice state=stopped
  sudo: yes
- name: Stop advanalytics.
  service: name=advanalytics state=stopped
  sudo: yes
- name: Stop impalasimulation.
  service: name=impalasimulation state=stopped
  sudo: yes
# - name: Start mathservice (upstart).
#   service: name=mathservice state=started
#   sudo: yes

- name: Get Compiler Module
  shell: aws s3 --region {{ region }} cp s3://{{ s3_deployment_bucket }}/{{ BuildVersion }}Baaz-Compiler.tar.gz .
- name: Remove the existing compiler deployed code
  file: path=/usr/lib/baaz_compiler state=absent
  sudo: yes
- name: Untar Compiler binaries
  shell: tar -zxf /home/ubuntu/Baaz-Compiler.tar.gz chdir=/usr/lib
  sudo: yes
- name: Get Compiler Service
  shell: aws s3 --region {{ region }} cp s3://{{ s3_deployment_bucket }}/{{ BuildVersion }}Baaz-Compile-Service.tar.gz .
- name: Install Compiler Service
  shell: tar -zxf /home/ubuntu/Baaz-Compile-Service.tar.gz chdir=/
  sudo: yes
- name: copy logback file
  template: src=logback.xml dest=/usr/lib/baaz_compiler/
  sudo: yes
- name: Stop any previous compile server that may be installed.
  service: name=compileserver state=stopped
  ignore_errors: yes
  sudo: yes
- name: Remove any previous compile server that may be installed.
  file: path=/etc/init/compileserver.conf state=absent
  sudo: yes
- name: Stop compileservice.
  service: name=compileservice state=stopped
  sudo: yes
- name: Stop advanalytics_compiler
  service: name=advanalytics_compiler state=stopped
  sudo: yes
- name: Stop compileservice_compiler
  service: name=compileservice_compiler state=stopped
  sudo: yes
- name: Stop applicationservice_compiler
  service: name=applicationservice_compiler state=stopped
  sudo: yes
- name: Stop elasticpub
  service: name=elasticpub state=stopped
  sudo: yes
# - name: Start compileserver.
#   service: name=compileserver state=started
#   sudo: yes
# - name: Start compileservice.
#   service: name=compileservice state=started
#   sudo: yes
- name: copy monitrc file
  template: src=roles/backoffice/files/monitrc dest=/etc/monit/monitrc
  sudo: yes
#- name: Start hive server
#  action: service name=hive state=started
#  sudo: yes
- name: Install Pip
  apt: name=python-pip state=present
  sudo: yes
- name: Install Elasticsearch
  pip: name=elasticsearch
  sudo: yes
- name: Install pandas python module
  apt: name=python-pandas state=present
  sudo: yes
- name: Install thrift
  pip: name=thrift version=0.9.3
  sudo: yes
- name: Install httplib2
  pip: name=httplib2
  sudo: yes
- name: install graphviz
  apt: name=graphviz update_cache=yes state=present
  sudo: yes
- name: install python-dev
  apt: name=python-dev state=present
  sudo: yes
- name: install libgraphviz-dev
  apt: name=libgraphviz-dev update_cache=yes
  sudo: yes
- name: install pkg-config
  apt: name=pkg-config update_cache=yes
  sudo: yes
- name: Install pygraphviz
  pip: name=pygraphviz
  sudo: yes
- name: Install redis
  pip: name=redis
  sudo: yes
- name: Install python-logstash
  pip: name=python-logstash
  sudo: yes
- name: Install binaryornot
  pip: name=binaryornot
  sudo: yes
- name: Upgrade pymongo to 3.0
  pip: name=pymongo state=latest
  sudo: yes
- name: Install python logger package
  pip: name=rlog
  sudo: yes
- name: Install python mock package
  pip: name=mock
  sudo: yes
- name: Install python six package
  pip: name=six extra_args='--upgrade'
  sudo: yes
- name: Install python pbr package
  pip: name=pbr
  sudo: yes
- name: Install python funcsigs package
  pip: name=funcsigs
  sudo: yes
- name: Install python datadog package
  pip: name=datadog
  sudo: yes
- name: Install python boto3 package
  pip: name=boto3
  sudo: yes
- name: Install python protobuf package
  pip: name=protobuf
  sudo: yes
- name: Install python grpcio package
  pip: name=grpcio
  sudo: yes
- name: Install boto
  pip: name=boto
  sudo: yes
- name: Install pika
  pip: name=pika version=0.9.8
  sudo: yes
- name: Install networkx
  pip: name=networkx
  sudo: yes
- name: Install sqlparse
  pip: name=sqlparse
  sudo: yes
- name: Install py_zipkin
  pip: name=py_zipkin
  sudo: yes
#REDIS SENTINEL DEPLOYMENT
#- name: Install Redis APT Package
#  apt: name=redis-server update_cache=yes
#  sudo: yes
#- name: Stop running redis server
#  service: name=redis-server state=stopped
#  sudo: yes
#- name: disable redis-server from init.d
#  shell: update-rc.d -f redis-server disable
#  sudo: yes
#  ignore_errors: True
#- name: remove redis-server from init.d
#  shell: update-rc.d -f redis-server remove
#  sudo: yes
#  ignore_errors: True
#- name: Create redis config directory
#  file: path=/etc/redis/local owner=redis group=redis mode=777 state=directory
#  sudo: yes
#- name: Create redis config directory
#  file: path=/var/log/sentinel owner=redis group=redis mode=777 state=directory
#  sudo: yes
#- name: Copy sentinel config file
#  template: src=roles/backoffice/templates/sentinel.conf dest=/etc/redis/local/sentinel.conf owner=redis group=redis mode=0644
#  sudo: yes
#- name: Write upstart script in /etc/init/redis-sentinel.conf
#  copy: src=roles/backoffice/files/redis-sentinel.conf dest=/etc/init/redis-sentinel.conf 
#  sudo: yes
#- name: Start sentinel
#  service: name=redis-sentinel state=started
#  sudo: yes
- name: Start monit service
  shell: monit 
  sudo: yes
- name: Reload monit
  shell: monit reload
  sudo: yes
# - name: Use monit to start all services
#   shell: monit start all
#   sudo: yes

#uncomment below change for impala enablement

