---
- name: Create the Baaz config directory
  file: path=/var/Baaz state=directory
  sudo: yes
- name: NTP installed
  apt: name=ntp update_cache=yes state=present
  sudo: yes
- name: Remove everything from under the /mnt/volumne1 directory
  shell: rm -rf /mnt/volume1/*
  sudo: yes
- name: Save configuration file
  template: src=hosts.cfg dest=/var/Baaz/hosts.cfg
  sudo: yes
- name: Get Flightpath
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}flightpath-deployment.tar.gz .
- name: Untar flightpath
  shell: tar -zxf /home/ubuntu/flightpath-deployment.tar.gz chdir=/
  sudo: yes
- name: Get Data Acquisition service
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-DataAcquisition-Service.tar.gz .
- name: Copy the service files
  shell: tar -zxf /home/ubuntu/Baaz-DataAcquisition-Service.tar.gz chdir=/
  sudo: yes
- name: Kill Monit so it won't interfere with installation
  shell: monit quit
  sudo: yes
- name: Remove old monit ID
  shell: rm -f /var/lib/monit/id
  sudo: yes
- name: Remove any previous service that may be installed.
  shell: update-rc.d -f baazdataacquisition remove
  sudo: yes
- name: Stop running upstart script
  service: name=dataacquisitionservice state=stopped
  sudo: yes
- name: Stop running upstart script
  service: name=applicationservice state=stopped
  sudo: yes
# - name: Start dataacquisitionservice (upstart).
#   service: name=dataacquisitionservice state=started
#   sudo: yes
- name: copy logrotate file
  template: src=roles/backoffice/files/compileserver dest=/etc/logrotate.d/
  sudo: yes

#Start of Analytics module deployment.
- name: Get Analytics Module
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Analytics.tar.gz .
- name: Untar Analytics
  shell: tar -zxf /home/ubuntu/Baaz-Analytics.tar.gz chdir=/
  sudo: yes
- name: Get Analytics Service
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Analytics-Service.tar.gz .
- name: Get Basestats 
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Basestats-Report.tar.gz .
- name: Install Basestats scripts
  shell: tar -zxf /home/ubuntu/Baaz-Basestats-Report.tar.gz chdir=/usr/lib
  sudo: yes
- name: Install Analytics Service
  shell: tar -zxf /home/ubuntu/Baaz-Analytics-Service.tar.gz chdir=/
  sudo: yes
- name: Remove any previous service that may be installed.
  shell: update-rc.d -f baazmath remove
  sudo: yes
- name: Stop mathservice.
  service: name=mathservice state=stopped
  sudo: yes
- name: Stop advanalytics.
  service: name=advanalytics state=stopped
  sudo: yes
- name: Stop impalasimulation.
  service: name=impalasimulation state=stopped
  sudo: yes
# - name: Start mathservice (upstart).
#   service: name=mathservice state=started
#   sudo: yes

- name: Get Compiler Module
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Compiler.tar.gz .
- name: Remove the existing compiler deployed code
  file: path=/usr/lib/baaz_compiler state=absent
  sudo: yes
- name: Untar Compiler binaries
  shell: tar -zxf /home/ubuntu/Baaz-Compiler.tar.gz chdir=/usr/lib
  sudo: yes
- name: Get Compiler Service
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Compile-Service.tar.gz .
- name: Install Compiler Service
  shell: tar -zxf /home/ubuntu/Baaz-Compile-Service.tar.gz chdir=/
  sudo: yes
- name: Remove any previous service that may be installed.
  shell: update-rc.d -f baazcompile remove
  sudo: yes
- name: Remove any previous xplaincompile server that may be installed.
  service: name=xplaincompile state=stopped
  ignore_errors: yes
  sudo: yes
- name: Delete xplaincompile.conf
  shell: rm -f /etc/init/xplaincompile.conf
  sudo: yes
- name: Stop compileservice.
  service: name=compileservice state=stopped
  sudo: yes
- name: Stop compileserver.
  service: name=compileserver state=stopped
  sudo: yes
# - name: Start compileserver.
#   service: name=compileserver state=started
#   sudo: yes
# - name: Start compileservice.
#   service: name=compileservice state=started
#   sudo: yes
- name: copy monitrc file
  template: src=roles/backoffice/files/monitrc dest=/etc/monit/monitrc
  sudo: yes
#- name: Start hive server
#  action: service name=hive state=started
#  sudo: yes
- name: Install Elasticsearch
  pip: name=elasticsearch
  sudo: yes

- name: Install httplib2
  pip: name=httplib2
  sudo: yes
- name: install graphviz
  apt: name=graphviz update_cache=yes
  sudo: yes
- name: install libgraphviz-dev
  apt: name=libgraphviz-dev update_cache=yes
  sudo: yes
- name: install pkg-config
  apt: name=pkg-config update_cache=yes
  sudo: yes
- name: Install pygraphviz
  pip: name=pygraphviz
  sudo: yes
- name: Install redis
  pip: name=redis
  sudo: yes
#REDIS SENTINEL DEPLOYMENT
#- name: Install Redis APT Package
#  apt: name=redis-server update_cache=yes
#  sudo: yes
#- name: Stop running redis server
#  service: name=redis-server state=stopped
#  sudo: yes
#- name: disable redis-server from init.d
#  shell: update-rc.d -f redis-server disable
#  sudo: yes
#  ignore_errors: True
#- name: remove redis-server from init.d
#  shell: update-rc.d -f redis-server remove
#  sudo: yes
#  ignore_errors: True
#- name: Create redis config directory
#  file: path=/etc/redis/local owner=redis group=redis mode=777 state=directory
#  sudo: yes
#- name: Create redis config directory
#  file: path=/var/log/sentinel owner=redis group=redis mode=777 state=directory
#  sudo: yes
#- name: Copy sentinel config file
#  template: src=roles/backoffice/templates/sentinel.conf dest=/etc/redis/local/sentinel.conf owner=redis group=redis mode=0644
#  sudo: yes
#- name: Write upstart script in /etc/init/redis-sentinel.conf
#  copy: src=roles/backoffice/files/redis-sentinel.conf dest=/etc/init/redis-sentinel.conf 
#  sudo: yes
#- name: Start sentinel
#  service: name=redis-sentinel state=started
#  sudo: yes

- name: Start monit service
  shell: monit 
  sudo: yes
# - name: Reload monit
#   shell: monit reload
#   sudo: yes
# - name: Use monit to start all services
#   shell: monit start all
#   sudo: yes

#uncomment below change for impala enablement

