---
- name: Update apt
  shell: apt-get update
  sudo: yes
- name: Install python setuptools
  apt: pkg=python-setuptools state=present
  sudo: yes
- name: Install pip
  shell: sudo easy_install pip
- name: Install pymongo
  shell: sudo pip install pymongo
- name: Install networkx
  shell: sudo pip install networkx
- name: Install pika
  shell: sudo pip install pika==0.9.8
- name: Install peewee
  shell: sudo pip install peewee
- name: Install sqlparse
  shell: sudo pip install sqlparse
- name: Install boto
  shell: sudo pip install boto
- name: Install S3 CMD
  apt: pkg=s3cmd state=present
  sudo: yes
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=/home/ubuntu/.s3cfg
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=~root/.s3cfg
  sudo: yes
- name: Copy boto config file
  copy: src=/home/ubuntu/.boto dest=/home/ubuntu/.boto
- name: Copy boto config file
  copy: src=/home/ubuntu/.boto dest=~root/.boto
  sudo: yes
- name: Get Flightpath
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}flightpath-deployment.tar.gz .
- name: Untar flightpath
  shell: tar -zxf /home/ubuntu/flightpath-deployment.tar.gz chdir=/
  sudo: yes
- name: Get Data Acquisition service
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-DataAcquisition-Service.tar.gz .
- name: Copy the service files
  shell: tar -zxf /home/ubuntu/Baaz-DataAcquisition-Service.tar.gz chdir=/
  sudo: yes
- name: Remove any previous service that may be installed.
  shell: update-rc.d -f baazdataacquisition remove
  sudo: yes
- name: Install baazdataacquisition Service.
  shell: update-rc.d baazdataacquisition defaults
  sudo: yes
- name: Start baazdataacquisition Service.
  service: name=baazdataacquisition state=restarted
  sudo: yes

#Start of Analytics module deployment.
- name: Get Analytics Module
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Analytics.tar.gz .
- name: Untar Analytics
  shell: tar -zxf /home/ubuntu/Baaz-Analytics.tar.gz chdir=/
  sudo: yes
- name: Get Analytics Service
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Analytics-Service.tar.gz .
- name: Get Basestats 
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Basestats-Report.tar.gz .
- name: Install Basestats scripts
  shell: tar -zxf /home/ubuntu/Baaz-Basestats-Report.tar.gz chdir=/usr/lib
  sudo: yes
- name: Install Monit service
  apt: pkg=monit state=present
  sudo: yes
- name: Install gcc needed for numpy
  apt: pkg=gcc state=present
  sudo: yes
- name: Install python-dev needed for numpy
  apt: pkg=python-dev state=present
  sudo: yes
- name: Install Mysql
  apt: pkg=mysql-server state=present
  sudo: yes
- name: Install python mysqldb
  apt: pkg=python-mysqldb state=present
  sudo: yes
- name: Mysql user addition
  mysql_user: name=baazdep password=baazdep priv=*.*:ALL state=present
- name: Mysql DB
  mysql_db: name=HADOOP_DEV state=present
- name: Install pika
  shell: sudo pip install numpy
- name: Install Analytics Service
  shell: tar -zxf /home/ubuntu/Baaz-Analytics-Service.tar.gz chdir=/
  sudo: yes
- name: Remove any previous service that may be installed.
  shell: update-rc.d -f baazmath remove
  sudo: yes
- name: Install baazmath Service.
  shell: update-rc.d baazmath defaults
  sudo: yes
- name: Start baazmath Service.
  service: name=baazmath state=restarted
  sudo: yes

#Start of Compiler module deployment.
- name: Install Java7
  apt: pkg=openjdk-7-jdk state=present
  sudo: yes
#- name: Download Hive-0.11
#  get_url: url=http://apache.tradebit.com/pub/hive/stable/hive-0.11.0.tar.gz  dest=/home/ubuntu/hive-0.11.0.tar.gz
#- name: Untar Hive 
#  shell: tar -zxf /home/ubuntu/hive-0.11.0.tar.gz chdir=/home/ubuntu/
#- name: Instal Hive
#  shell: mv /home/ubuntu/hive-0.11.0 /usr/lib/hive
#  sudo: yes
- name: Download Hive in /usr/local/
  command: chdir=/usr/local/ wget http://mirror.olnevhost.net/pub/apache/hive/hive-0.12.0/hive-0.12.0-bin.tar.gz
  sudo: yes
- name: Remove any existing hive directory
  file: path=/usr/local/hive-0.12.0-bin/ state=absent
  sudo: yes
  ignore_errors: True
- name: Untar Hive in /usr/local/
  command: chdir=/usr/local/ tar -xzf hive-0.12.0-bin.tar.gz
  sudo: yes
- name: Delete Hive tar file in /usr/local/
  command: chdir=/usr/local/ rm hive-0.12.0-bin.tar.gz
  sudo: yes
- name: Download Hadoop in /usr/local/
  command: chdir=/usr/local/ wget http://mirrors.advancedhosters.com/apache/hadoop/common/hadoop-0.23.10/hadoop-0.23.10.tar.gz
  sudo: yes
- name: Remove any existing hadoop directory
  file: path=/usr/local/hadoop-0.23.10/ state=absent
  sudo: yes
  ignore_errors: True
- name: Remove any existing hadoop link directory
  file: path=/usr/local/hadoop/ state=absent
  sudo: yes
  ignore_errors: True
- name: Untar hadoop in /usr/local/
  command: chdir=/usr/local/ tar -xzf hadoop-0.23.10.tar.gz
  sudo: yes
- name: Delete Hadoop tar file in /usr/local/
  command: chdir=/usr/local/ rm hadoop-0.23.10.tar.gz
  sudo: yes
- name: Create symbolic link for hadoop
  command: chdir=/usr/local/ ln -s hadoop-0.23.10 hadoop
  ignore_errors: True
  sudo: yes
- name: Create hive directory
  file: dest=/mnt/volume1/hive/ mode=0777 state=directory
  sudo: yes
- name: Create hive log directory
  file: dest=/var/log/hive/ mode=0777 state=directory
  sudo: yes
- name: Create hive warehouse directory
  file: dest=/mnt/volume1/warehouse/ mode=0777 state=directory
  sudo: yes
- name: Copy hive-site.xml to /usr/local/hive-0.12.0-bin/conf/
  copy: src=roles/backoffice/files/hive-site.xml dest=/usr/local/hive-0.12.0-bin/conf/hive-site.xml
  sudo: yes
- name: Mysql DB
  mysql_db: name=hadoop state=present
- name: Create mysql user hive 
  mysql_user: name=hive password=hive priv=hadoop.*:ALL state=present
- name: Install mysql connector into hive lib directory
  copy: src=roles/backoffice/files/mysql-connector-java-5.1.30-bin.jar dest=/usr/local/hive-0.12.0-bin/lib/
  sudo: yes
- name: install python hive client libraries
  shell: cp -r /usr/local/hive-0.12.0-bin/lib/py/* /usr/local/lib/python2.7/dist-packages/
  sudo: yes
- name: Install hive upstart script
  copy: src=roles/backoffice/files/hive.conf dest=/etc/init/
  sudo: yes
- name: Install xplaincompile server upstart script
  copy: src=roles/backoffice/files/xplaincompile.conf dest=/etc/init/
  sudo: yes

- name: Get Compiler Module
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Compiler.tar.gz .
- name: Untar Compiler binaries
  shell: tar -zxf /home/ubuntu/Baaz-Compiler.tar.gz chdir=/usr/lib
  sudo: yes
- name: Get Compiler Service
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Compile-Service.tar.gz .
- name: Install Compiler Service
  shell: tar -zxf /home/ubuntu/Baaz-Compile-Service.tar.gz chdir=/
  sudo: yes
- name: Remove any previous service that may be installed.
  shell: update-rc.d -f baazcompile remove
  sudo: yes
- name: Install baazcompile Service.
  shell: update-rc.d baazcompile defaults
  sudo: yes
- name: Start xplain compile server server
  action: service name=xplaincompile state=started
  sudo: yes
- name: Start Baaz Compiler Service.
  service: name=baazcompile state=restarted
  sudo: yes
- name: copy monitrc file
  template: src=roles/backoffice/files/monitrc dest=/etc/monit/monitrc
  sudo: yes
- name: Start hive server
  action: service name=hive state=started
  sudo: yes
- name: Start monit service
  shell: monit reload
  sudo: yes
