---
- name: Create the Baaz config directory
  file: path=/var/Baaz state=directory
  sudo: yes
- name: Create mount point
  file: path=/mnt/volume1 owner=ubuntu group=ubuntu state=directory
  sudo: yes
- name: Mount /dev/xvdc
  mount: name=/mnt/volume1 src=/dev/xvdc fstype=ext3 state=mounted
  sudo: yes
- name: Set the timezone
  shell: echo "America/Los_Angeles" | sudo tee /etc/timezone
- name: Reset the system time to new timezone.
  shell: dpkg-reconfigure --frontend noninteractive tzdata
  sudo: yes
- name: Save configuration file
  template: src=hosts.cfg dest=/var/Baaz/hosts.cfg
  sudo: yes
- name: Get Flightpath
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}flightpath-deployment.tar.gz .
- name: Untar flightpath
  shell: tar -zxf /home/ubuntu/flightpath-deployment.tar.gz chdir=/
  sudo: yes
- name: Get Data Acquisition service
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-DataAcquisition-Service.tar.gz .
- name: Copy the service files
  shell: tar -zxf /home/ubuntu/Baaz-DataAcquisition-Service.tar.gz chdir=/
  sudo: yes
- name: Remove any previous service that may be installed.
  shell: update-rc.d -f baazdataacquisition remove
  sudo: yes
- name: Install baazdataacquisition Service.
  shell: update-rc.d baazdataacquisition defaults
  sudo: yes
- name: Start baazdataacquisition Service.
  service: name=baazdataacquisition state=restarted
  sudo: yes

#Start of Analytics module deployment.
- name: Get Analytics Module
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Analytics.tar.gz .
- name: Untar Analytics
  shell: tar -zxf /home/ubuntu/Baaz-Analytics.tar.gz chdir=/
  sudo: yes
- name: Get Analytics Service
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Analytics-Service.tar.gz .
- name: Get Basestats 
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Basestats-Report.tar.gz .
- name: Install Basestats scripts
  shell: tar -zxf /home/ubuntu/Baaz-Basestats-Report.tar.gz chdir=/usr/lib
  sudo: yes
- name: Install Analytics Service
  shell: tar -zxf /home/ubuntu/Baaz-Analytics-Service.tar.gz chdir=/
  sudo: yes
- name: Remove any previous service that may be installed.
  shell: update-rc.d -f baazmath remove
  sudo: yes
- name: Install baazmath Service.
  shell: update-rc.d baazmath defaults
  sudo: yes
- name: Start baazmath Service.
  service: name=baazmath state=restarted
  sudo: yes
- name: Install xplaincompile server upstart script
  copy: src=roles/backoffice/files/xplaincompile.conf dest=/etc/init/
  sudo: yes

- name: Get Compiler Module
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Compiler.tar.gz .
- name: Untar Compiler binaries
  shell: tar -zxf /home/ubuntu/Baaz-Compiler.tar.gz chdir=/usr/lib
  sudo: yes
- name: Get Compiler Service
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}Baaz-Compile-Service.tar.gz .
- name: Install Compiler Service
  shell: tar -zxf /home/ubuntu/Baaz-Compile-Service.tar.gz chdir=/
  sudo: yes
- name: Remove any previous service that may be installed.
  shell: update-rc.d -f baazcompile remove
  sudo: yes
- name: Install baazcompile Service.
  shell: update-rc.d baazcompile defaults
  sudo: yes
- name: Stop xplain compile server server
  action: service name=xplaincompile state=stopped
  sudo: yes
- name: Start xplain compile server server
  action: service name=xplaincompile state=started
  sudo: yes
- name: Start Baaz Compiler Service.
  service: name=baazcompile state=restarted
  sudo: yes
- name: copy monitrc file
  template: src=roles/backoffice/files/monitrc dest=/etc/monit/monitrc
  sudo: yes
- name: Start hive server
  action: service name=hive state=started
  sudo: yes
- name: Start monit service
  shell: monit reload
  sudo: yes
