---
- name: Install python setuptools
  apt: pkg=python-setuptools state=present
  sudo: yes
- name: Install pip
  shell: sudo easy_install pip
- name: Install pymongo
  shell: sudo pip install pymongo
- name: Install networkx
  shell: sudo pip install networkx
- name: Install S3 CMD
  apt: pkg=s3cmd state=present
  sudo: yes
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=/home/ubuntu/.s3cfg
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=~root/.s3cfg
  sudo: yes
- name: Get Flightpath
  shell: s3cmd sync s3://baaz-deployment/flightpath-deployment.tar.gz .
- name: Untar flightpath
  shell: tar -zxf /home/ubuntu/flightpath-deployment.tar.gz chdir=/
  sudo: yes
- name: Get Scheduled Parsing
  shell: s3cmd sync s3://baaz-deployment/Scheduled-deployment.tar.gz .
- name: Untar Scheduled
  shell: tar -zxf /home/ubuntu/Scheduled-deployment.tar.gz chdir=/
  sudo: yes
- name: start cron job
  cron: name="Parse Files" minute="55" job="/usr/local/bin/hourly.sh  >> /tmp/cronlog 2>&1"
  sudo: yes

