datadog_config:
  tags: "{{ datadog_tag }}, log, redis"
datadog_checks:
  disk:
    init_config:
    instances:
      - use_mount: no
  process:
    init_config:
    instances:
    - name: ssh
      search_string: ['ssh', 'sshd']
  redisdb:
    init_config:
    instances:
    - host: localhost
      port: 6379
