---
- name: Prepare file system
  filesystem: fstype=ext3 dev=/dev/xvdb
  sudo: yes
- name: Create mount point
  file: path=/mnt/volume1 owner=ubuntu group=ubuntu state=directory
  sudo: yes
- name: Mount EBS
  mount: name=/mnt/volume1 src=/dev/xvdb fstype=ext3 state=mounted
  sudo: yes
- name: Change ownsership of volume1
  file: path=/mnt/volume1 owner=ubuntu group=ubuntu state=directory
  sudo: yes
- name: Create the Baaz config directory
  file: path=/var/Baaz state=directory
  sudo: yes
- name: Save configuration file
  template: src=hosts.cfg dest=/var/Baaz/hosts.cfg
  sudo: yes
- name: Set the timezone
  shell: echo "America/Los_Angeles" | sudo tee /etc/timezone 
- name: Reset the system time to new timezone.
  shell: dpkg-reconfigure --frontend noninteractive tzdata
  sudo: yes
