---
# This Playbook would deploy the whole Baazdata cluster with replication and sharding.


- hosts: localhost
  tasks:
  - name: Create mount point
    file: path=/mnt/volume1 owner=xplain group=xplain state=directory
  - name: Set Mongodb Repo Keyserver
    shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - name: Set Mongodb repo list
    shell: echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list 
  - name: Add repo for nodejs
    apt_repository: repo='ppa:chris-lea/node.js' state=present
  - name: Update apt
    shell: apt-get update
  - name: Install Mongodb
    shell: apt-get install mongodb-10gen
  - name: Install Nodejs
    apt: pkg=nodejs state=present
  - name: Create Mongo log
    file: path=/mnt/volume1/mongo/log owner=xplain group=xplain state=directory
  - name: Create Mongo db
    file: path=/mnt/volume1/mongo/db owner=xplain group=xplain state=directory
  - name: Install python setuptools
    apt: pkg=python-setuptools state=present
  - name: Install python dev
    apt: pkg=python-dev state=present
  - name: Install pip
    shell: easy_install pip
  - name: Disable wheels (pip 1.5 bug workaround)
    shell: pip install setuptools --no-use-wheel --upgrade
  - name: Install pymongo
    shell: pip install pymongo
  - name: Install peewee
    shell: pip install peewee
  - name: Install networkx
    shell: pip install networkx
  - name: Install pika
    shell: pip install pika==0.9.8
  - name: Install numpy
    shell: pip install numpy

    #Start of Analytics module deployment.
  - name: Install gcc needed for numpy
    apt: pkg=gcc state=present
  - name: Install python-dev needed for numpy
    apt: pkg=python-dev state=present
  - name: Install numpy
    shell: pip install numpy
  - name: Install Mysql
    apt: pkg=mysql-server state=present
  - name: Install python mysqldb
    apt: pkg=python-mysqldb state=present
  - name: Install sqlparse
    shell: pip install sqlparse

    #Start of Compiler module deployment.
  - name: Install Java7
    apt: pkg=openjdk-7-jdk state=present

  - name: Install python setuptools
    apt: pkg=python-setuptools state=present
  - name: Install graphviz
    apt: pkg=graphviz state=present
    ignore_errors: True
  - name: Install libgraphviz-dev
    apt: pkg=libgraphviz-dev state=present
  - name: Install pip
    shell: easy_install pip
  - name: Install pymongo
    shell: pip install pymongo
  - name: Install networkx
    shell: pip install networkx
  - name: Install python mysqlDB
    apt: pkg=python-mysqldb state=present
  - name: Add rabbitMQ Repo 
    shell: echo "deb http://www.rabbitmq.com/debian/ testing main" >> /etc/apt/sources.list
  - name: Set rabbitmq public key
    shell: wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
  - name: Add rabbit MQ key
    shell: apt-key add rabbitmq-signing-key-public.asc
  - name: update APT
    shell: apt-key update
  - name: Install Rabbit MQ
    apt: pkg=rabbitmq-server state=present
  - name: Copy node upstart configuration file
    copy: src=/home/xplain/nodejs.conf dest=/etc/init/nodejs.conf
  - name: Download Hive in /usr/local/
    command: chdir=/usr/local/ wget http://mirror.olnevhost.net/pub/apache/hive/hive-0.12.0/hive-0.12.0-bin.tar.gz
    sudo: yes
  - name: Untar Hive in /usr/local/
    command: chdir=/usr/local/ tar -xzf hive-0.12.0-bin.tar.gz
    sudo: yes
  - name: Delete Hive tar file in /usr/local/
    command: chdir=/usr/local/ rm hive-0.12.0-bin.tar.gz
    sudo: yes
  - name: Download Hadoop in /usr/local/
    command: chdir=/usr/local/ wget http://mirrors.advancedhosters.com/apache/hadoop/common/hadoop-0.23.10/hadoop-0.23.10.tar.gz
    sudo: yes
  - name: Untar hadoop in /usr/local/
    command: chdir=/usr/local/ tar -xzf hadoop-0.23.10.tar.gz
    sudo: yes
  - name: Delete Hadoop tar file in /usr/local/
    command: chdir=/usr/local/ rm hadoop-0.23.10.tar.gz
    sudo: yes
  - name: Create symbolic link for hadoop
    command: chdir=/usr/local/ ln -s hadoop-0.23.10 hadoop
    ignore_errors: True
    sudo: yes 
  - name: Create hive directory
    file: dest=/mnt/volume1/hive 
  - name: Create hive log directory
    file: dest=/var/log/hive 
  - name: Create hive warehouse directory
    file: dest=/mnt/volume1/warehouse mode=0777
    sudo: yes
  - name: Copy hive-site.xml to /usr/local/hive-0.12.0-bin/conf/
    copy: src=/home/xplain/hive-site.xml dest=/usr/local/hive-0.12.0-bin/conf/hive-site.xml
  - name: Change mysql root user password
    mysql_user: name=root password=mysql
  - name: Mysql DB
    mysql_db: name=hadoop login_user=root login_password=mysql state=present
  - name: Install mysql connector into hive lib directory
    copy: src=/home/xplain/mysql-connector-java-5.1.30-bin.jar dest=/usr/local/hive-0.12.0-bin/lib/
  - name: install python hive client libraries
    synchronize: src=/usr/local/hive-0.12.0-bin/lib/py/ dest=/usr/local/lib/python2.7/dist-packages/
  - name: Install hive upstart script
    copy: src=/home/xplain/hive.conf dest=/etc/init/
    sudo: yes
  - name: Start hive server
    action: service name=hive state=started
  - name: Install Monit service
    apt: pkg=monit state=present
  - name: Change desktop background
    shell: gsettings set org.gnome.desktop.background picture-uri file://home/xplain/Slpash.png
