---
# This Playbook would deploy the whole Baazdata cluster with replication and sharding.


- hosts: localhost
  tasks:
  - name: Start Mongo
    shell: mongod --fork --logpath /mnt/volume1/mongo/log/mongo.log -dbpath /mnt/volume1/mongo/db
    ignore_errors: True

  - name: Untar flightpath
    shell: tar -zxf /home/xplain/flightpath-deployment.tar.gz chdir=/
  - name: Copy the service files
    shell: tar -zxf /home/xplain/Baaz-DataAcquisition-Service.tar.gz chdir=/
  - name: Remove any previous service that may be installed.
    shell: update-rc.d -f baazdataacquisition remove
  - name: Install baazdataacquisition Service.
    shell: update-rc.d baazdataacquisition defaults
  - name: Start baazdataacquisition Service.
    service: name=baazdataacquisition state=started

    #Start of Analytics module deployment.
  - name: Untar Analytics
    shell: tar -zxf /home/xplain/Baaz-Analytics.tar.gz chdir=/
  - name: Install Basestats scripts
    shell: tar -zxf /home/xplain/Baaz-Basestats-Report.tar.gz chdir=/usr/lib
  - name: Mysql user addition
    mysql_user: name=baazdep password=baazdep login_user=root login_password=mysql priv=*.*:ALL state=present
  - name: Mysql DB
    mysql_db: name=HADOOP_DEV login_user=root login_password=mysql state=present
  - name: Install Analytics Service
    shell: tar -zxf /home/xplain/Baaz-Analytics-Service.tar.gz chdir=/
  - name: Remove any previous service that may be installed.
    shell: update-rc.d -f baazmath remove
  - name: Install baazmath Service.
    shell: update-rc.d baazmath defaults
  - name: Start baazmath Service.
    service: name=baazmath state=started

    #Start of Compiler module deployment.
  - name: Untar Compiler binaries
    shell: tar -zxf /home/xplain/Baaz-Compiler.tar.gz chdir=/usr/lib
  - name: Install Compiler Service
    shell: tar -zxf /home/xplain/Baaz-Compile-Service.tar.gz chdir=/
  - name: Remove any previous service that may be installed.
    shell: update-rc.d -f baazcompile remove
  - name: Install baazcompile Service.
    shell: update-rc.d baazcompile defaults
  - name: Install xplaincompile server upstart script
    copy: src=/home/xplain/xplaincompile.conf dest=/etc/init/
  - name: Start xplain compile server
    action: service name=xplaincompile state=started
  - name: Start Baaz Compiler Service.
    service: name=baazcompile state=started

  - name: Create mysql user
    mysql_user: name=baaz password=baaz login_user=root login_password=mysql priv=*.*:ALL state=present
  - name: Create mysql DB
    mysql_db: name=baazdata login_user=root login_password=mysql state=present
  - name: Untar flightpath
    shell: tar -zxf /home/xplain/flightpath-deployment.tar.gz chdir=/
  - name: Copy node upstart configuration file
    copy: src=/home/xplain/nodejs.conf dest=/etc/init/nodejs.conf
  - name: Untar Baazdata App
    shell: tar -zxf /home/xplain/xplain.io.tar.gz
  - name: Remove the existing deployed code
    file: path=/var/xplain state=absent
  - name: Move the new code
    shell: mv /home/xplain/xplain.io /var/xplain
  - name: Install npm modules.
    npm: path=/var/xplain
  - name: copy monitrc file
    copy: src=/home/xplain/monitrc dest=/etc/monit/monitrc
