---
# This Playbook would deploy the whole Baazdata cluster with replication and sharding.


- hosts: localhost
  tasks:
  - name: Create mount point
    file: path=/mnt/volume1 owner=ubuntu group=ubuntu state=directory
  - name: Set Mongodb Repo Keyserver
    shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - name: Set Mongodb repo list
    shell: echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list 
  - name: Update apt
    shell: apt-get update
  - name: Install Mongodb
    shell: apt-get install mongodb-10gen
  - name: Create Mongo log
    file: path=/mnt/volume1/mongo/log owner=ubuntu group=ubuntu state=directory
  - name: Create Mongo db
    file: path=/mnt/volume1/mongo/db owner=ubuntu group=ubuntu state=directory
  - name: Start Mongo
    shell: mongod --fork --logpath /mnt/volume1/mongo/log/mongo.log -dbpath /mnt/volume1/mongo/db
    ignore_errors: True

  - name: Install python setuptools
    apt: pkg=python-setuptools state=present
  - name: Install pip
    shell: easy_install pip
  - name: Disable wheels (pip 1.5 bug workaround)
    shell: pip install setuptools --no-use-wheel --upgrade
  - name: Install pymongo
    shell: pip install pymongo
  - name: Install peewee
    shell: pip install peewee
  - name: Install networkx
    shell: pip install networkx
  - name: Install pika
    shell: pip install pika==0.9.8
  - name: Untar flightpath
    shell: tar -zxf /home/ubuntu/flightpath-deployment.tar.gz chdir=/
  - name: Copy the service files
    shell: tar -zxf /home/ubuntu/Baaz-DataAcquisition-Service.tar.gz chdir=/
  - name: Remove any previous service that may be installed.
    shell: update-rc.d -f baazdataacquisition remove
  - name: Install baazdataacquisition Service.
    shell: update-rc.d baazdataacquisition defaults
  - name: Start baazdataacquisition Service.
    service: name=baazdataacquisition state=started

    #Start of Analytics module deployment.
  - name: Untar Analytics
    shell: tar -zxf /home/ubuntu/Baaz-Analytics.tar.gz chdir=/
  - name: Install Basestats scripts
    shell: tar -zxf /home/ubuntu/Baaz-Basestats-Report.tar.gz chdir=/usr/lib
  - name: Install gcc needed for numpy
    apt: pkg=gcc state=present
  - name: Install python-dev needed for numpy
    apt: pkg=python-dev state=present
  - name: Install Mysql
    apt: pkg=mysql-server state=present
  - name: Install python mysqldb
    apt: pkg=python-mysqldb state=present
  - name: Mysql user addition
    mysql_user: name=baazdep password=baazdep priv=*.*:ALL state=present
  - name: Mysql DB
    mysql_db: name=HADOOP_DEV state=present
  - name: Install pika
    shell: pip install numpy
  - name: Install sqlparse
    shell: pip install sqlparse
  - name: Install Analytics Service
    shell: tar -zxf /home/ubuntu/Baaz-Analytics-Service.tar.gz chdir=/
  - name: Remove any previous service that may be installed.
    shell: update-rc.d -f baazmath remove
  - name: Install baazmath Service.
    shell: update-rc.d baazmath defaults
  - name: Start baazmath Service.
    service: name=baazmath state=started

    #Start of Compiler module deployment.
  - name: Install Java7
    apt: pkg=openjdk-7-jdk state=present
  - name: Untar Compiler binaries
    shell: tar -zxf /home/ubuntu/Baaz-Compiler.tar.gz chdir=/usr/lib
  - name: Install Compiler Service
    shell: tar -zxf /home/ubuntu/Baaz-Compile-Service.tar.gz chdir=/
  - name: Remove any previous service that may be installed.
    shell: update-rc.d -f baazcompile remove
  - name: Install baazxompile Service.
    shell: update-rc.d baazcompile defaults
  - name: Start Baaz Compiler Service.
    service: name=baazcompile state=started

  - name: Install mysql server
    apt: pkg=mysql-server state=present
  - name: Install python setuptools
    apt: pkg=python-setuptools state=present
  - name: Install graphviz
    apt: pkg=graphviz state=present
    ignore_errors: True
  - name: Install libgraphviz-dev
    apt: pkg=libgraphviz-dev state=present
  - name: Install pip
    shell: easy_install pip
  - name: Install pymongo
    shell: pip install pymongo
  - name: Install networkx
    shell: pip install networkx
  - name: Install python mysqlDB
    apt: pkg=python-mysqldb state=present
  - name: Create mysql user
    mysql_user: name=baaz password=baaz priv=*.*:ALL state=present
  - name: Create mysql DB
    mysql_db: name=baazdata state=present
  - name: Untar flightpath
    shell: tar -zxf /home/ubuntu/flightpath-deployment.tar.gz chdir=/
  - name: Add rabbitMQ Repo 
    shell: echo "deb http://www.rabbitmq.com/debian/ testing main" >> /etc/apt/sources.list
  - name: Set rabbitmq public key
    shell: wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
  - name: Add rabbit MQ key
    shell: apt-key add rabbitmq-signing-key-public.asc
  - name: update APT
    shell: apt-key update
  - name: Install Rabbit MQ
    apt: pkg=rabbitmq-server state=present
  - name: Copy node upstart configuration file
    copy: src=/home/ubuntu/nodejs.conf dest=/etc/init/nodejs.conf
  - name: Install Monit service
    apt: pkg=monit state=present
  - name: Untar Baazdata App
    shell: tar -zxf /home/ubuntu/xplain.io.tar.gz
  - name: Remove the existing deployed code
    file: path=/var/xplain state=absent
  - name: Move the new code
    shell: mv /home/ubuntu/xplain.io /var/xplain
  - name: copy monitrc file
    copy: src=/home/ubuntu/monitrc dest=/etc/monit/monitrc
