---
- name: Add JRE ppa
  apt_repository: repo=ppa:webupd8team/java state=present
- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
- name: Install JRE
  apt: pkg=oracle-java7-installer state=latest update-cache=yes force=yes
- name: Get Elasticsearch Package
  get_url: url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.1.1.deb dest=/home/xplain
- name: Install Elasticsearch
  shell: dpkg -i elasticsearch-1.1.1.deb
  sudo: yes
- name: Configure update-rc.d
  shell: update-rc.d elasticsearch defaults 95 10
  sudo: yes
- name: Install Mapper-Attachments Plugin
  shell: /usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-mapper-attachments/2.0.0
  sudo: yes
  ignore_errors: true
- name: Install MongoDB River Plugin
  shell: /usr/share/elasticsearch/bin/plugin --install com.github.richardwilly98.elasticsearch/elasticsearch-river-mongodb/2.0.0
  sudo: yes
  ignore_errors: true
- name: Install EC2 Plugin
  shell: /usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-cloud-aws/2.1.1
  sudo: yes
  ignore_errors: true
- name: Start Elasticsearch Service
  service: name=elasticsearch state=started
  sudo: yes
- name: Install monit service
  apt: pkg=monit state=present
  sudo: yes
- name: copy monitrc file
  template: src=roles/elasticsearch/files/monitrc dest=/etc/monit/monitrc
  sudo: yes
- name: Start monit service
  shell: monit reload
  sudo: yes
- name: install python dev
  shell: apt-get install python-dev -y
  sudo: yes
- name: install s3cmd
  shell: pip install s3cmd
  sudo: yes
- name: uninstall pika
  shell: pip uninstall pika -y
  sudo: yes
- name: install pika
  shell: pip install -I pika==0.9.8
  sudo: yes
- name: install s3cmd
  shell: pip install pymongo
  sudo: yes
- name: install s3cmd
  shell: pip install redis
  sudo: yes
- name: install networkx
  pip: name=networkx
  sudo: yes
- name: Install python logger package
  pip: name=rlog
  sudo: yes
- name: Install python mock package
  pip: name=mock
  sudo: yes
- name: Install python six package
  pip: name=six extra_args='--upgrade'
  sudo: yes
- name: Install python pbr package
  pip: name=pbr
  sudo: yes
- name: Install python funcsigs package
  pip: name=funcsigs
  sudo: yes
- name: Copy s3cfg
  copy: src=~/.s3cfg dest=/home/ubuntu/
  sudo: yes
- name: Get Flightpath
  shell: s3cmd sync s3://baaz-deployment/flightpath-deployment.tar.gz /home/ubuntu/
  sudo: no
- name: Untar flightpath
  shell: tar -zxf /home/ubuntu/flightpath-deployment.tar.gz -C /
  sudo: yes
- name: Copy host file
  shell: mkdir -p /var/Baaz
  sudo: yes
- name: Copy host file
  copy: src=hosts.cfg dest=/var/Baaz/hosts.cfg
  sudo: yes
- name: Copy Elastic service
  copy: src=ElasticPubService.py dest=/usr/local/bin/ElasticPubService.py
  sudo: yes
- name: Change Elastic service permission
  shell: chmod +x /usr/local/bin/ElasticPubService.py
  sudo: yes
- name: Copy Elastic upstart
  copy: src=elasticpub.conf dest=/etc/init/elasticpub.conf
  sudo: yes
- name: Stop running upstart script
  service: name=elasticpub state=stopped
  sudo: yes
- name: Start running upstart script
  service: name=elasticpub state=started
  sudo: yes
