---
### DEPENDENCIES ###
- name: Install S3 CMD
  apt: name=s3cmd state=present update_cache=yes
  sudo: yes
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=/home/bitnami/.s3cfg
### SET UP ENVIRONMENT ###
- name: Create the Baaz config directory
  file: path=/var/Baaz state=directory mode=777
  sudo: yes
- name: Remove the existing deployed code
  file: path=/var/exec state=absent
  sudo: yes
### UNPACK S3 TARBALLS ###
- name: Get Exec Dashboard
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}exec_dashboard.tar.gz .
- name: Remove everything from under the /tmp directory
  shell: rm -rf /tmp/*
  sudo: yes
- name: Untar exec App
  shell: tar -zxf /home/bitnami/exec_dashboard.tar.gz
- name: Move the new exec code
  shell: cp -a /home/bitnami/exec_dashboard/. /var/exec/
  sudo: yes
- name: Create log folders
  file: path=/var/exec/log state=directory owner=bitnami mode=755
  sudo: yes
### DEPLOY AND CONFIGURE ###
- name: Disable default binami
  shell: /opt/bitnami/ctlscript.sh stop
  sudo: yes
- name: Template and copy nginx conf file
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  sudo: yes
- name: Save configuration file
  template: src=hosts.cfg dest=/var/Baaz/hosts.cfg
  sudo: yes
- name: Get xplain cert
  template: src=/etc/nginx/ssl/xplain_san_cert.crt dest=/etc/nginx/ssl/
  sudo: yes
- name: Get Cloudera Key
  template: src=/etc/nginx/ssl/san_cloudera_com.key dest=/etc/nginx/ssl/
  sudo: yes
- name: Create dir for logs
  file: path=/var/log/cloudera/navopt/nodejs state=directory owner=bitnami mode=755
  sudo: yes
