---
### DEPENDENCIES ###
- name: Install S3 CMD
  apt: name=s3cmd state=present update_cache=yes
  sudo: yes
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=/home/ubuntu/.s3cfg
### SET UP ENVIRONMENT ###
- name: Create the Baaz config directory
  file: path=/var/Baaz state=directory mode=777
  sudo: yes
- name: Remove the existing deployed code
  file: path=/var/exec state=absent
  sudo: yes
- name: Mkdir exec
  file: path=/var/exec state=directory
  sudo: yes
### UNPACK S3 TARBALLS ###
- name: Get Exec Dashboard
  shell: s3cmd sync s3://{{ s3_deployment_bucket }}/{{ BuildVersion }}exec_dashboard.tar.gz .
- name: Remove everything from under the /tmp directory
  shell: rm -rf /tmp/*
  sudo: yes
- name: Untar exec App
  shell: tar -zxf /home/ubuntu/exec_dashboard.tar.gz
- name: Move the new exec code
  shell: cp -a /home/ubuntu/exec_dashboard/. /var/exec/
  sudo: yes
- name: Get Flightpath
  shell: s3cmd sync s3://{{ s3_deployment_bucket }}/{{ BuildVersion }}flightpath-deployment.tar.gz .
- name: Untar flightpath
  shell: tar -zxf /home/ubuntu/flightpath-deployment.tar.gz chdir=/
  sudo: yes
- name: Create log folders
  file: path=/var/exec/log state=directory owner=ubuntu mode=755
  sudo: yes
### DEPLOY AND CONFIGURE ###
- name: Save configuration file
  template: src=hosts.cfg dest=/var/Baaz/hosts.cfg
  sudo: yes
- name: Create dir for logs
  file: path=/var/log/cloudera/navopt/nodejs state=directory owner=ubuntu mode=755
  sudo: yes
- name: Install pandas python module
  apt: name=python-pandas state=present
  sudo: yes
- name: Install pip python module
  apt: name=python-pip state=present
  sudo: yes
- name: Install dev python module
  apt: name=python-dev state=present
  sudo: yes
- name: Install Elasticsearch
  pip: name=elasticsearch
  sudo: yes
- name: Install networkx
  pip: name=networkx
  sudo: yes
- name: Install boto
  pip: name=boto
  sudo: yes
- name: Install bottle
  pip: name=bottle
  sudo: yes
- name: Install thrift
  pip: name=thrift version=0.9.3
  sudo: yes
- name: Install httplib2
  pip: name=httplib2
  sudo: yes
- name: install graphviz
  apt: name=graphviz update_cache=yes
  sudo: yes
- name: install libgraphviz-dev
  apt: name=libgraphviz-dev update_cache=yes
  sudo: yes
- name: install pkg-config
  apt: name=pkg-config update_cache=yes
  sudo: yes
- name: Install pygraphviz
  pip: name=pygraphviz
  sudo: yes
- name: Install redis
  pip: name=redis
  sudo: yes
- name: Install python-logstash
  pip: name=python-logstash
  sudo: yes
- name: Install binaryornot
  pip: name=binaryornot
  sudo: yes
- name: Upgrade pymongo to 3.0
  pip: name=pymongo state=latest
  sudo: yes
- name: Install python logger package
  pip: name=rlog
  sudo: yes
- name: Install python mock package
  pip: name=mock
  sudo: yes
- name: Install python six package
  pip: name=six extra_args='--upgrade'
  sudo: yes
- name: Install python pbr package
  pip: name=pbr
  sudo: yes
- name: Install python funcsigs package
  pip: name=funcsigs
  sudo: yes
- name: Install python datadog package
  pip: name=datadog
  sudo: yes
