---
- name: Update apt
  shell: apt-get update
  sudo: yes
- name: Create the Baaz config directory
  file: path=/var/Baaz state=directory
  sudo: yes
- name: Set the timezone
  shell: echo "America/Los_Angeles" | sudo tee /etc/timezone 
- name: Reset the system time to new timezone.
  shell: dpkg-reconfigure --frontend noninteractive tzdata
  sudo: yes
- name: Create mount point
  file: path=/mnt/volume1 owner=ubuntu group=ubuntu state=directory
  sudo: yes
- name: Install python setuptools
  apt: pkg=python-setuptools state=present
  sudo: yes
- name: Install pip
  shell: sudo easy_install pip
- name: Install pymongo
  shell: sudo pip install pymongo
- name: Install networkx
  shell: sudo pip install networkx
- name: Install pika
  shell: sudo pip install pika==0.9.8
- name: Install peewee
  shell: sudo pip install peewee
- name: Install sqlparse
  shell: sudo pip install sqlparse
- name: Install boto
  shell: sudo pip install boto
- name: Install S3 CMD
  apt: pkg=s3cmd state=present
  sudo: yes
- name: Install sasl dependency..
  command: apt-get install python-dev libsasl2-dev gcc g++
  sudo: yes
  ignore_errors: True
- name: Install sasl
  pip: name=sasl
  sudo: yes
  ignore_errors: True
- name: Install impyla
  pip: name=impyla
  sudo: yes
  ignore_errors: True
- name: Install pyhs2
  pip: name=pyhs2
  sudo: yes
  ignore_errors: True
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=/home/ubuntu/.s3cfg
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=~root/.s3cfg
  sudo: yes
- name: Copy boto config file
  copy: src=/home/ubuntu/.boto dest=/home/ubuntu/.boto
- name: Copy boto config file
  copy: src=/home/ubuntu/.boto dest=~root/.boto
  sudo: yes

- name: Install Monit service
  apt: pkg=monit state=present
  sudo: yes
- name: Install gcc needed for numpy
  apt: pkg=gcc state=present
  sudo: yes
- name: Install python-dev needed for numpy
  apt: pkg=python-dev state=present
  sudo: yes
- name: Install Mysql
  apt: pkg=mysql-server state=present
  sudo: yes
- name: Install python mysqldb
  apt: pkg=python-mysqldb state=present
  sudo: yes
- name: Install redis python client
  pip: name=redis
  sudo: yes
- name: Install Java repo
  command: add-apt-repository -y ppa:webupd8team/java
  sudo: yes
- name: Run the update
  command: apt-get update
  sudo: yes
  ignore_errors: True
- name: Update config for java update
  shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
- name: Install java version
  command: apt-get install -y oracle-jdk7-installer
  sudo: yes
- name: Set JAVA HOME
  shell: JAVA_HOME="/usr/lib/jvm/java-7-oracle"
  sudo: yes
- name: Change the permission of /etc/enviornment file
  command: chmod 666 /etc/environment
  sudo: yes
- name: update /etc/enviornment file with java info
  command: echo "JAVA_HOME=\"/usr/lib/jvm/java-7-oracle\"" >> /etc/environment
  sudo: yes
