---
### DEPENDENCIES ###
- name: Install S3 CMD
  apt: name=s3cmd state=present
  sudo: yes
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=/home/bitnami/.s3cfg
- name: NTP installed
  apt: name=ntp state=present
  sudo: yes
- name: Add nginx ppa
  apt_repository: repo='ppa:nginx/stable'
  sudo: yes
- name: Install nginx
  apt: name=nginx state=present
  sudo: yes
### SET UP ENVIRONMENT ###
- name: Stop admin_nodejs
  service: name=admin_nodejs state=stopped
  sudo: yes
  ignore_errors: true
- name: Create the Baaz config directory
  file: path=/var/Baaz state=directory mode=777
  sudo: yes
- name: Remove the existing deployed code
  file: path=/var/admin state=absent
  sudo: yes
- name: Create /var/admin
  file: path=/var/admin state=directory owner=bitnami mode=755
  sudo: yes
- name: Create /etc/nginx/ssl
  file: path=/etc/nginx/ssl state=directory owner=bitnami mode=755
  sudo: yes
### UNPACK S3 TARBALLS ###
- name: Get Optimizer Admin
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}optimizer_admin.io.tar.gz .
- name: Remove everything from under the /tmp directory
  shell: rm -rf /tmp/*
  sudo: yes
- name: Untar Optimizer Admin App
  shell: tar -zxf /home/bitnami/optimizer_admin.io.tar.gz
- name: Move the new admin code
  shell: cp -a /home/bitnami/optimizer_admin/. /var/admin/
  sudo: yes
- name: Create log folders
  file: path=/var/admin/log state=directory owner=bitnami mode=755
  sudo: yes
- name: Move the new node code
  shell: mv /home/bitnami/optimizer_admin/config/* /var/admin/config/
  sudo: yes
- name: Install the s3 configuration file
  template: src=s3.json dest=/var/admin/config/s3.json
  sudo: yes
- name: Get the npm modules.
  npm: path=/var/admin
### Ansibleception
- name: Copy ansible folders
  copy: src=/etc/ansible dest=/etc/ owner=bitnami mode=755
  sudo: yes
- name: Create create deployement dir
  file: path=/boot/build state=directory owner=bitnami mode=755
  sudo: yes
- name: Create create deployement dir2
  file: path=/boot/build/deployement state=directory owner=bitnami mode=755
  sudo: yes
- name: Copy deployment scripts
  copy: src=/mnt/build/deployment/playbooks dest=/boot/build/deployement/ owner=bitnami mode=755
  sudo: yes
### DEPLOY AND CONFIGURE ###
- name: Disable default binami
  shell: /opt/bitnami/ctlscript.sh stop
  sudo: yes
- name: Create username/password for nginx
  command: /usr/bin/htpasswd -b -c /etc/nginx/.htpasswd xplain xplainio
  sudo: yes
- name: Create node admin upstart script
  template: src=admin_nodejs.conf dest=/etc/init/admin_nodejs.conf
  sudo: yes
- name: Template and copy nginx conf file
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  sudo: yes
- name: Save configuration file
  template: src=hosts.cfg dest=/var/Baaz/hosts.cfg
  sudo: yes
- name: Get xplain cert
  template: src=/etc/nginx/ssl/xplain_san_cert.crt dest=/etc/nginx/ssl/
  sudo: yes
- name: Get Cloudera Key
  template: src=/etc/nginx/ssl/san_cloudera_com.key dest=/etc/nginx/ssl/
  sudo: yes
- name: Start admin nodejs
  service: name=admin_nodejs state=started
  sudo: yes
- name: Start nginx
  command: /usr/sbin/nginx
  sudo: yes
  ignore_errors: yes
- name: Reload nginx
  command: /usr/sbin/nginx -s reload
  sudo: yes
