---
- name: Add logstash apt key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
- name: Add logstash apt repository to sources list
  apt_repository: repo='deb http://packages.elasticsearch.org/logstash/1.5/debian stable main' state=present
- name: Install logstash 
  apt: name=logstash state=present update_cache=yes
- name: Template logstash config file
  template: src=logstash-backoffice.conf dest=/etc/logstash/conf.d/logstash-backoffice.conf
- name: Restart logstash
  service: name=logstash state=restarted
  