---
- name: Add nginx ppa
  apt_repository: repo='ppa:nginx/stable'
  sudo: yes
- name: Install nginx
  apt: name=nginx state=present
  sudo: yes
- name: Create /var/www
  file: path=/var/www state=directory
  sudo: yes
- name: Template and copy nginx conf file
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  sudo: yes
- name: Start nginx
  command: /usr/sbin/nginx
  sudo: yes
  ignore_errors: yes
- Reload nginx
  command: /usr/sbin/nginx -s reload
  sudo: yes