#!/bin/bash

set -eux

BRANCH=$1

mkdir UI && git -C /gitcache/UI archive $BRANCH | tar -x -C UI

mkdir deployment
git -C /gitcache/deployment archive $BRANCH | tar -x -C deployment
cp deployment/scripts/gulp-config.js ./
cp deployment/scripts/gulpfile.js ./
cp deployment/scripts/package.json ./
ln -s /usr/bin/nodejs /usr/bin/node
npm install
gulp app-build


echo "--- building UI..."
cd UI/webapp/war #Are we even ever using this? This looks very legacy, going to delete this assuming deployment goes fine
tar -zcf /target/UI.tar.gz ./UI/*
cd ../..

#tar -zcf /target/xplain.io.tar.gz ./UI/xplain.io This is now being generated by gulp
tar -zcf /target/optimizer_api.io.tar.gz ./UI/optimizer_api
tar -zcf /target/xplain_dashboard.tar.gz ./UI/xplain_dashboard
tar -zcf /target/optimizer_admin.io.tar.gz ./UI/optimizer_admin
