#!/bin/bash
#
# chkconfig: 35 90 12
# Default-Start: 3 4 5
# Default-Stop: 0 1 2
# description: Foo server
#
# Get function from functions library
#. /etc/init.d/functions
# Start the service baaz
start() {
        initlog -c "echo -n Starting baaz server: "
        /usr/local/bin/baazmonitor.sh &
        ### Create the lock file ###
        touch /var/lock/baaz
        success $"baaz server startup"
        echo
}
# Restart the service baaz
stop() {
        initlog -c "echo -n Stopping baaz server: "
        killall baazmonitor.sh
        ### Now, delete the lock file ###
        rm -f /var/lock/baaz
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status baaz
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
