---
- name: Get Flightpath
  shell: aws s3 --region {{ region }} sync s3://{{ s3_deployment_bucket }}/{{ BuildVersion }}flightpath-deployment.tar.gz /home/ubuntu/
  sudo: no
- name: Untar flightpath
  shell: tar -zxf /home/ubuntu/flightpath-deployment.tar.gz -C /
  sudo: yes
- name: install networkx
  pip: name=networkx
  sudo: yes
- name: Install Elasticsearch
  pip: name=elasticsearch
  sudo: yes
# === Below requirements.txt dependecies is broken on ubunutu 14.10 works fine 14.04 ====

#- name: install graphviz
#  apt: name=graphviz update_cache=yes
#  sudo: yes
#- name: install libgraphviz-dev
#  apt: name=libgraphviz-dev update_cache=yes
#  sudo: yes
#- name: install pkg-config
#  apt: name=pkg-config update_cache=yes
#  sudo: yes
#- name: Install Requriment for our app
#  pip: requirements=AMI-scripts/backoffice_base/requirements.txt chdir=/mnt/build/deployment
#  sudo: yes
- name: copy user activity script to crontab folder
  copy: src=../emailjobs/GetUserActivity.py dest=/etc/cron.weekly/GetUserActivity
  sudo: yes
- name: change permission
  command: chmod +x /etc/cron.weekly/GetUserActivity
  sudo: yes
- name: copy failure upload script to crontab folder
  copy: src=../emailjobs/failureUpdateEmail.py dest=/etc/cron.daily/failureUpdateEmail
  sudo: yes
- name: change permission
  command: chmod +x /etc/cron.daily/failureUpdateEmail
  sudo: yes
- name: copy upload script to crontab folder
  copy: src=../emailjobs/uploadUpdateEmail.py dest=/etc/cron.daily/uploadUpdateEmail
  sudo: yes
- name: change permission
  command: chmod +x /etc/cron.daily/uploadUpdateEmail
  sudo: yes
