---
- name: Stop the apache service
  shell: /opt/bitnami/ctlscript.sh stop apache
  sudo: yes
- name: Create the Baaz config directory
  file: path=/var/Baaz state=directory
  sudo: yes
- name: Update apt
  shell: apt-get update
  sudo: yes
- name: Save configuration file
  template: src=hosts.cfg dest=/var/Baaz/hosts.cfg
  sudo: yes
- name: Install S3 CMD
  apt: pkg=s3cmd state=present
  sudo: yes
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=/home/bitnami/.s3cfg
- name: Get Baazdata App
  shell: s3cmd sync s3://baaz-deployment/xplain.io.tar.gz .
- name: Untar Baazdata App
  shell: tar -zxf /home/bitnami/xplain.io.tar.gz
- name: Start the service
  shell: chdir=/home/bitnami/xplain.io nohup node server.js &
  sudo: yes
