---
### DEPENDENCIES ###
- name: Install S3 CMD
  apt: name=s3cmd state=present
  sudo: yes
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=/home/bitnami/.s3cfg
- name: NTP installed
  apt: name=ntp state=present
  sudo: yes
- name: Install Monit service
  apt: pkg=monit state=present
  sudo: yes
### SET UP ENVIRONMENT ###
- name: Stop nodejs
  service: name=nodejs state=stopped
  sudo: yes
  ignore_errors: true
- name: Create the Baaz config directory
  file: path=/var/Baaz state=directory mode=0644
  sudo: yes
- name: Create /var/xplain{{ port }}
  file: path=/var/xplain{{ port }} state=directory owner=root mode=0644
  sudo: yes
### UNPACK S3 TARBALLS ###
- name: Get Baazdata App
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}xplain.io.tar.gz .
- name: Untar Baazdata App
  shell: tar -zxf /home/bitnami/xplain.io.tar.gz
- name: Remove the existing deployed code
  file: path=/var/xplain{{ port }} state=absent
  sudo: yes
- name: Move the new code
  shell: mv /home/bitnami/xplain.io /var/xplain{{ port }}
  sudo: yes
- name: Get the npm modules.
  npm: path=/var/xplain{{ port }}
### DEPLOY AND CONFIGURE ###
- name: Create node upstart script
  template: src=nodejs.conf dest=/etc/init/nodejs.conf
  sudo: yes
- name: Save configuration file
  template: src=hosts.cfg dest=/var/Baaz/hosts.cfg
  sudo: yes
- name: Start nodejs
  service: name=nodejs state=started
  sudo: yes
- name: copy monitrc file
  template: src=roles/nodejsserver/files/monitrc dest=/etc/monit/monitrc
  sudo: yes
- name: Start monit service
  shell: monit reload
  sudo: yes


