---
- name: Stop the apache service
  shell: /opt/bitnami/ctlscript.sh stop apache
  sudo: yes
- name: Set the timezone
  shell: echo "America/Los_Angeles" | sudo tee /etc/timezone 
- name: Reset the system time to new timezone.
  shell: dpkg-reconfigure --frontend noninteractive tzdata
  sudo: yes
- name: Create the Baaz config directory
  file: path=/var/Baaz state=directory
  sudo: yes
- name: Copy node upload configuration file
  copy: src=roles/nodejsserver/files/nodejs.conf dest=/etc/init/nodejs.conf
  sudo: yes
- name: Update apt
  shell: apt-get update
  sudo: yes
- name: Save configuration file
  template: src=hosts.cfg dest=/var/Baaz/hosts.cfg
  sudo: yes
- name: Install S3 CMD
  apt: pkg=s3cmd state=present
  sudo: yes
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=/home/bitnami/.s3cfg
- name: Install Monit service
  apt: pkg=monit state=present
  sudo: yes
- name: Get Baazdata App
  shell: s3cmd sync s3://baaz-deployment/{{ BuildVersion }}xplain.io.tar.gz .
- name: Untar Baazdata App
  shell: tar -zxf /home/bitnami/xplain.io.tar.gz
- name: Remove the existing deployed code
  file: path=/var/xplain state=absent
  sudo: yes
- name: Move the new code
  shell: mv /home/bitnami/xplain.io /var/xplain
  sudo: yes
- name: Get the npm modules.
  npm: path=/var/xplain
- name: Stop the service
  shell: stop nodejs
  sudo: yes
  ignore_errors: True
- name: Start the service
  shell: start nodejs
  sudo: yes
- name: copy monitrc file
  template: src=roles/nodejsserver/files/monitrc dest=/etc/monit/monitrc
  sudo: yes
- name: Start monit service
  shell: monit reload
  sudo: yes
