---
- name: Set Mongodb Repo Keyserver
  shell: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
- name: Set Mongodb repo list
  shell: echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list 
- name: Update apt
  shell: sudo apt-get update
- name: Install Mongodb
  shell: sudo apt-get install mongodb-10gen
- name: Create Mongo log
  file: path=/mnt/volume1/mongo/log owner=ubuntu group=ubuntu state=directory
- name: Create Mongo db
  file: path=/mnt/volume1/mongo/db owner=ubuntu group=ubuntu state=directory
- name: Start Mongo
  shell: mongod --fork --logpath /mnt/volume1/mongo/log/mongo.log -dbpath /mnt/volume1/mongo/db
  ignore_errors: True
