---
#- name: Set Mongodb Repo Keyserver
#  shell: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
#- name: Set Mongodb repo list
#  shell: echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list 
#- name: Update apt
#  apt: update_cache=yes
#  sudo: yes
#- name: Install Mongodb
#  apt: name=mongodb-org state=present
#  sudo: yes
#- name: Install Monit service
#  apt: pkg=monit state=present
#  sudo: yes
#- name: Copy Mongodb config
#  copy: src=roles/mongodb/files/mongodb.conf dest=/etc/mongod.conf
#  sudo: yes
- name: Create Mongo log
  file: path=/mnt/volume1/mongo/log owner=mongodb state=directory
  sudo: yes
- name: Create Mongo db
  file: path=/mnt/volume1/mongo/db owner=mongodb state=directory
  sudo: yes
- name: Create the file to initialize the mongod replica set
  template: src=replica_set.j2 dest=/tmp/repset_init.js
- name: Start Mongo
  service: name=mongod state=stopped
  sudo: yes
  ignore_errors: true
- name: Start Mongo
  service: name=mongod state=started
  sudo: yes
- name: Pause for a while
  pause: seconds=20
- name: Initialize the replication set
  shell: /usr/bin/mongo /tmp/repset_init.js 
- name: copy monitrc file
  template: src=roles/mongodb/files/monitrc dest=/etc/monit/monitrc
  sudo: yes
- name: Start monit service
  shell: monit reload
  sudo: yes
