#!/bin/bash

set -e

ROOT=`pwd`/`dirname $0`
ACCOUNT=$1

if [ -z "$ACCOUNT" ]; then
	echo "account must be specified" 1>&2
	exit 1
fi

shift

case $ACCOUNT in
	dev|dev-us-west-2)
		ACCOUNT=dev-us-west-2
		export AWS_PROFILE=navopt_dev
		;;

	stage|stage-us-west-2)
		ACCOUNT=stage-us-west-2
		export AWS_PROFILE=navopt_stage
		;;

	alpha|alpha-us-west-2)
		ACCOUNT=alpha-us-west-2
		export AWS_PROFILE=navopt_prod
		;;

	*)
		echo "unknown account '$ACCOUNT'" 1>&2
		exit 1
		;;
esac

ACCOUNT_ROOT=$ROOT/accounts/$ACCOUNT
export EC2_INI_PATH=$ROOT/accounts/ec2.ini
export ANSIBLE_CONFIG=$ACCOUNT_ROOT/ansible.cfg

exec $ROOT/venv/bin/ansible-playbook \
	-i $ACCOUNT_ROOT/inventory \
	$ROOT/site.yml \
	"$@"
