---
# This Playbook would deploy the whole Baazdata cluster with replication and sharding.
# Before running this playbook, make sure old scripts have been stopped with scripts/stop-old-scripts.yml

- hosts: tag_Name_Backoffice
  roles:
  - role: s3cmd
  - role: backoffice

- hosts: tag_Name_QueueServer
  roles:
  - role: mtpereira.erlang
    become: yes
  - role: Stouts.rabbitmq
    rabbitmq_vhosts:
    - xplain
    rabbitmq_plugins:
    - rabbitmq_management
    rabbitmq_users:
    - user: "{{ rabbitmq_username }}"
      password: "{{ rabbitmq_password }}"
      vhost: xplain
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present
    - user: "{{ rabbitmq_username }}"
      password: "{{ rabbitmq_password }}"
      vhost: xplain
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      tags: administrator
      state: present
    become: yes
  - role: queueserver

- hosts: tag_Name_NodeJS
  roles:
  - role: s3cmd
  - role: nodejsserver

- hosts: tag_Name_APIServer
  roles:
  - role: api

- hosts: tag_Name_AdminServer
  roles:
  - role: s3cmd
  - role: admin

- hosts: tag_Name_ExecServer
  roles:
  - role: exec

- hosts: tag_Name_Nginx
  roles:
  - role: nginx

- hosts: tag_Name_RedisCache
  roles:
  - role: redis
    sudo: true

- hosts: tag_Name_KibanaAndElasticsearch
  roles:
  - role: elasticlog
    sudo: true
  - role: kibana
    sudo: true

- hosts: tag_Name_LogstashServer
  roles:
  - role: logstash
    sudo: true

- hosts: tag_Name_RedisLog
  roles:
  - role: redislog
    sudo: true

- hosts: tag_Name_Bastion
  roles:
  - role: dashboard_server
    tags: ['dasbboard']
    sudo: true
  - role: cronjobs
    tags: ['crons']
    sudo: true
  - role: monit_collector #TODO needs to add this
    tags: ['monit_data']
    sudo: true

- hosts: tag_Name_Datadog
  roles:
  - role: Datadog.datadog
    sudo: true

- hosts: tag_Name_Docker
  roles:
  - role: angstwad.docker_ubuntu
    sudo: true
