---
# This Playbook would deploy the whole Baazdata cluster with replication and sharding.
# Before running this playbook, make sure old scripts have been stopped with scripts/stop-old-scripts.yml

- hosts: tag_Name_MongoDBServer
  roles:
  - role: common
  - role: mongodb

- hosts: tag_Name_Backoffice
  serial: 4
  roles:
  - role: backoffice

- hosts: tag_Name_Webserver1
  roles:
  - role: webserver

- hosts: tag_Name_QueueServer
  roles:
  - role: queueserver

- hosts: tag_Name_NodeJS
  serial: 1
  roles:
  - role: nodejsserver

- hosts: tag_Name_APIServer
  roles:
  - role: api

- hosts: tag_Name_AdminServer
  roles:
  - role: admin

- hosts: tag_Name_ExecServer
  roles:
  - role: exec

- hosts: tag_Name_Nginx
  roles:
  - role: nginx

- hosts: tag_Name_Foundation
  roles:
  - role: foundation

- hosts: tag_Name_Redis
  roles:
  - role: redis
    sudo: true

- hosts: tag_Name_RedisCache
  roles:
  - role: redis
    sudo: true

- hosts: tag_Name_ElasticSearch
  roles:
  - role: elasticsearch
    sudo: true

- hosts: tag_Name_DeploymentRoot
  roles:
  - role: deploymentroot

- hosts: tag_Name_RedisSentinel
  roles:
  - role: redis_sentinel
    sudo: true

- hosts: tag_Name_KibanaAndElasticsearch
  roles:
  - role: elasticlog
    sudo: true
  - role: kibana
    sudo: true

- hosts: tag_Name_LogstashServer
  roles:
  - role: logstash
    sudo: true

- hosts: tag_Name_RedisLog
  roles:
  - role: redislog
    sudo: true

- hosts: tag_Name_Bastion
  roles:
  - role: dashboard_server
    tags: ['dasbboard']
    sudo: true
  - role: cronjobs
    tags: ['crons']
    sudo: true
  - role: monit_collector #TODO needs to add this
    tags: ['monit_data']
    sudo: true

- hosts: tag_Name_Datadog
  roles:
  - role: Datadog.datadog
    sudo: true

- hosts: tag_Name_Docker
  roles:
  - role: angstwad.docker_ubuntu
    sudo: true