#!/bin/bash
#
# chkconfig: 35 90 12
# Default-Start: 3 4 5
# Default-Stop: 0 1 2
# description: Foo server
#
# Get function from functions library
#. /etc/init.d/functions
# Start the service baazcompile
start() {
        initlog -c "echo -n Starting baazcompile server: "
        /usr/local/bin/BaazCompileService.py &
        echo $! > /var/run/BaazCompileService.pid
        ### Create the lock file ###
        touch /var/lock/baazcompile
        #success $"baaz server startup"
        echo
}
# Restart the service baazmath
stop() {
        #initlog -c "echo -n Stopping baazcompile server: "
        killall BaazCompileService.py
        ### Now, delete the lock file ###
        rm -f /var/lock/baazcompile
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status baazcompile
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
