---
- name: Create the Baaz config directory
  file: path=/var/Baaz state=directory
  sudo: yes
- name: Save configuration file
  template: src=hosts.cfg dest=/var/Baaz/hosts.cfg
  sudo: yes
- name: copy emails.cfg to /var/Baaz
  template: src=emails.cfg dest=/var/Baaz/emails.cfg
  sudo: yes
- name: copy sender.txt.enc to /var/Baaz
  copy: src=/home/ubuntu/build/deployment/playbooks/roles/deploymentroot/files/sender.txt.enc dest=/var/Baaz/sender.txt.enc
  sudo: yes
- name: copy python files
  copy: src=/home/ubuntu/build/deployment/emailjobs/ dest=/home/ubuntu/siddharth/emailjobs/
- name: Install S3 CMD
  apt: pkg=s3cmd state=present
  sudo: yes
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=/home/ubuntu/.s3cfg
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=~root/.s3cfg
  sudo: yes
- name: Get Flightpath
  shell: s3cmd sync s3://baaz-deployment/flightpath-deployment.tar.gz .
- name: Untar flightpath
  shell: tar -zxf /home/ubuntu/flightpath-deployment.tar.gz chdir=/
  sudo: yes
- name: install pymongo
  pip: name=pymongo
  sudo: yes
- name: install networkx
  pip: name=networkx
  sudo: yes
- name: install redis py
  pip: name=redis
  sudo: yes
- name: change update email file to executables
  file: path=/home/ubuntu/siddharth/emailjobs/uploadUpdateEmail.py owner=ubuntu group=ubuntu mode=0755
- name: change failure email file to executables
  file: path=/home/ubuntu/siddharth/emailjobs/failureUpdateEmail.py owner=ubuntu group=ubuntu mode=0755
#- cron: name="update email job" hour="*/12" job="/home/ubuntu/siddharth/emailjobs/uploadUpdateEmails.py"
#- cron: name="failure email job" minute="*/2" job="/home/ubuntu/siddharth/emailjobs/failureUpdateEmails.py"
- name: Add nginx ppa
  apt_repository: repo='ppa:nginx/stable'
  sudo: yes
- name: Install nginx
  apt: name=nginx update_cache=yes
  sudo: yes
- name: Install apache2-utils
  apt: name=apache2-utils state=present
- name: Copy nginx conf file
  copy: src=/home/ubuntu/build/deployment/playbooks/roles/deploymentroot/files/nginx.conf dest=/etc/nginx/nginx.conf
  sudo: yes
- name: Create /var/www dir
  file: path=/var/www state=directory
  sudo: yes
- name: Copy index.html file
  copy: src=/home/ubuntu/build/deployment/playbooks/roles/deploymentroot/files/index.html dest=/var/www/index.html
  sudo: yes
- name: Stop nodejs
  service: name=nodejs state=stopped
  sudo: yes
- name: Copy new node upstart script
  copy: src=/home/ubuntu/build/deployment/playbooks/roles/deploymentroot/files/nodejs.conf dest=/etc/init/nodejs.conf
  sudo: yes
- name: Start nodejs
  service: name=nodejs state=started
  sudo: yes
- name: Create username/password
  command: /usr/bin/htpasswd -b -c /etc/nginx/.htpasswd xplain xplainio
  sudo: yes 
- name: Start nginx
  command: /usr/sbin/nginx
  sudo: yes
- name: Reload nginx
  command: /usr/sbin/nginx -s reload
  sudo: yes
