---
- name: copy emails.cfg to /var/Baaz
  template: emails.cfg dest=/var/Baaz/emails.cfg
  sudo: yes
- name: copy sender.txt.enc to /var/Baaz
  copy: src=/home/ubuntu/build/playbooks/roles/deploymentroot/files/sender.txt.enc dest=/var/Baaz/sender.txt.enc
  sudo: yes
- name: copy python files
  copy: src=/home/ubuntu/build/emailjobs/ dest=/home/ubuntu/siddharth/emailjobs/ state=directory
- name: Get Flightpath
  shell: s3cmd sync s3://baaz-deployment/flightpath-deployment.tar.gz .
- name: Untar flightpath
  shell: tar -zxf /home/ubuntu/flightpath-deployment.tar.gz chdir=/
  sudo: yes