---
- name: copy emails.cfg to /var/Baaz
  template: src=emails.cfg dest=/var/Baaz/emails.cfg
  sudo: yes
- name: copy sender.txt.enc to /var/Baaz
  copy: src=/home/ubuntu/build/deployment/playbooks/roles/deploymentroot/files/sender.txt.enc dest=/var/Baaz/sender.txt.enc
  sudo: yes
- name: copy python files
  copy: src=/home/ubuntu/build/deployment/emailjobs/ dest=/home/ubuntu/siddharth/emailjobs/
- name: Install S3 CMD
  apt: pkg=s3cmd state=present
  sudo: yes
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=/home/ubuntu/.s3cfg
- name: Copy s3cmd config file
  copy: src=/home/ubuntu/.s3cfg dest=~root/.s3cfg
  sudo: yes
- name: Get Flightpath
  shell: s3cmd sync s3://baaz-deployment/flightpath-deployment.tar.gz .
- name: Untar flightpath
  shell: tar -zxf /home/ubuntu/flightpath-deployment.tar.gz chdir=/
  sudo: yes
- name: install pymongo
  pip: name=pymongo
  sudo: yes
- name: install networkx
  pip: name=networkx
  sudo: yes
- name: install redis py
  pip: name=redis
  sudo: yes
- name: change update email file to executables
  file: path=/home/ubuntu/siddharth/emailjobs/uploadUpdateEmail.py owner=ubuntu group=ubuntu mode=0755
- name: change failure email file to executables
  file: path=/home/ubuntu/siddharth/emailjobs/failureUpdateEmail.py owner=ubuntu group=ubuntu mode=0755
#- cron: name="update email job" hour="*/12" job="/home/ubuntu/siddharth/emailjobs/uploadUpdateEmails.py"
#- cron: name="failure email job" minute="*/2" job="/home/ubuntu/siddharth/emailjobs/failureUpdateEmails.py"